// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovdujjdkllucjlzargsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92ZHVqamRrbGx1Y2psemFyZ3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDgyMTgsImV4cCI6MjA2MTIyNDIxOH0.11kUh3ineB0G_PcGjuvGvNpNtqyreasokSqyPqs3RoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);